=== dorsin555/822-126/xml xsd demo/people.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.eldar.org/people"
	xmlns:tns="http://www.eldar.org/people" elementFormDefault="qualified">


	<!-- schema rulls -->
	<element name="people">
		<complexType>
			<sequence>
				<element name="person" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="id" type="int"></element>
							<element name="name" type="tns:name-eldar"></element>
							<element name="age" type="tns:age-eldar"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>


	<!-- schema types -->
	<simpleType name="age-eldar">
		<restriction base="int">
			<minInclusive value="0"></minInclusive>
			<maxInclusive value="120"></maxInclusive>
		</restriction>
	</simpleType>

	<simpleType name="name-eldar">
		<restriction base="string">
			<maxLength value="10"></maxLength>
		</restriction>
	</simpleType>



</schema>

=== dorsin555/822-126/xml xsd demo/people.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- well formed xml - correct XML syntax -->
<!-- valid xml requires schema - another documentation for rules -->
<people xmlns="http://www.eldar.org/people"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.eldar.org/people people.xsd">
	<person>
		<id>101</id>
		<name>aaaaaaaaaa</name>
		<age>120</age>
	</person>
	<person>
		<id>102</id>
		<name>bbb</name>
		<age>32</age>
	</person>
</people>
